global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'lychee-nft-platform'
    environment: 'production'

# 告警规则文件
rule_files:
  # - "alerts/*.yml"

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter - 系统指标
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          instance: 'lychee-server'

  # PostgreSQL Exporter - 数据库指标
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          database: 'lychee_db'

  # Redis Exporter - 缓存指标
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # Backend API - 应用指标
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:4000']
        labels:
          service: 'backend'
          app: 'lychee-api'

  # Nginx - Web 服务器指标
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
        labels:
          service: 'nginx'

# 远程写入配置（可选 - 用于长期存储）
# remote_write:
#   - url: "http://remote-storage:9009/api/v1/push"

# 远程读取配置（可选）
# remote_read:
#   - url: "http://remote-storage:9009/api/v1/read"
